#!/usr/bin/env bash


### Create a database backup.
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) postgres backup


set -o errexit
set -o pipefail
set -o nounset


working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"


message_welcome "Backing up the '' database..."

export PGUSER="${POSTGRESQL_USER}"
export PGDATABASE="${POSTGRESQL_DATABASE}"

backup_filename="${BACKUP_FILE_PREFIX}_${PROJECT_NAME}_$(date +'%Y_%m_%dT%H_%M_%S').dmp"
pg_dump -Fc -Oxv > "${BACKUP_DIR_PATH}/${backup_filename}"


message_success "'${POSTGRESQL_DATABASE}' database backup '${backup_filename}' has been created and placed in '${BACKUP_DIR_PATH}'."
