#!/usr/bin/env bash


### Restore database from a backup.
###
### Parameters:
###     <1> filename of an existing backup.
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) postgres restore <1>


set -o errexit
set -o pipefail
set -o nounset


working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"


if [[ -z ${1+x} ]]; then
    message_error "Backup filename is not specified yet it is a required parameter. Make sure you provide one and try again."
    exit 1
fi
backup_filename="${BACKUP_DIR_PATH}/${1}"
if [[ ! -f "${backup_filename}" ]]; then
    message_error "No backup with the specified filename found. Check out the 'backups' maintenance script output to see if there is one and try again."
    exit 1
fi

message_welcome "Restoring the '${POSTGRESQL_DATABASE}' database from the '${backup_filename}' backup..."

export PGUSER="${POSTGRESQL_USER}"
export PGDATABASE="${POSTGRESQL_DATABASE}"

message_info "Dropping the schema..."
psql -c "drop schema public cascade"

message_info "Creating new schema..."
psql -c "create schema public"

message_info "Applying the backup to the new database..."
pg_restore -Fc -Oxv -d "${POSTGRESQL_DATABASE}" "${backup_filename}"

message_success "The '${POSTGRESQL_DATABASE}' database has been restored from the '${backup_filename}' backup."
