# Generated by Django 3.1.3 on 2021-01-14 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_event_categories_data'),
        ('account', '0006_account_is_late_with_club_membership_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oris_id', models.PositiveIntegerField(unique=True)),
                ('oris_category_id', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField()),
                ('oris_created', models.DateTimeField(blank=True, null=True)),
                ('oris_updated', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='account.account')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='event.event')),
            ],
        ),
    ]
