# Generated by Django 3.1.3 on 2021-04-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='rent_si',
            field=models.BooleanField(default=False),
        ),
    ]
