# Generated by Django 3.1.3 on 2021-05-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_entry_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
