# Generated by Django 3.1.3 on 2021-09-14 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_entry_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='oris_club_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
