# Generated by Django 3.1.3 on 2021-09-30 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_auto_20210914_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='debt_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='other_debt',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
