# Generated by Django 3.1.3 on 2022-10-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_auto_20210930_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='oris_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
