# Generated by Django 3.2.18 on 2026-07-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_auto_20221019_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='services_only',
            field=models.BooleanField(default=False),
        ),
    ]
