# Generated by Django 3.1.3 on 2020-11-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories_data',
            field=models.JSONField(default=dict),
        ),
    ]
