# Generated by Django 3.1.3 on 2021-01-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_is_late_with_club_membership_payment'),
        ('event', '0002_event_categories_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
