# Generated by Django 3.1.3 on 2021-04-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210308_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_date_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='entry_date_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='entry_date_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
