# Generated by Django 3.1.3 on 2021-04-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210405_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_bank_account',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
