# Generated by Django 3.1.3 on 2021-05-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_entry_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='links',
            field=models.JSONField(default=dict),
        ),
    ]
