# Generated by Django 3.1.3 on 2021-05-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_services',
            field=models.JSONField(default=dict),
        ),
    ]
