# Generated by Django 3.1.3 on 2021-05-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_additional_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bills_solved',
            field=models.BooleanField(default=False),
        ),
    ]
