# Generated by Django 3.1.3 on 2021-09-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_bills_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='processing_state',
            field=models.CharField(choices=[('UNPROCESSED', 'Nezpracován'), ('PAYMENT_INFO_EMAIL_SENT', 'Odeslán příkaz k platbě'), ('LEADER_EMAIL_SENT', 'Odeslán email vedoucímu'), ('BILLS_SOLVED', 'Dluhy spočteny')], default='UNPROCESSED', max_length=50),
        ),
    ]
