# Generated by Django 3.1.3 on 2021-09-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_event_processing_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bills_solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='processing_state',
            field=models.CharField(choices=[('UNPROCESSED', 'Nezpracován'), ('PAYMENT_INFO_EMAIL_SENT', 'Odeslán příkaz k platbě'), ('LEADER_EMAIL_SENT', 'Odeslán email vedoucímu'), ('BILLS_EMAIL_SENT', 'Odeslány dluhy vedoucímu'), ('BILLS_SOLVED', 'Dluhy spočteny')], default='UNPROCESSED', max_length=50),
        ),
    ]
