# Generated by Django 3.2.18 on 2023-04-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20210928_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='handled_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
