# Generated by Django 3.2.18 on 2026-03-25 21:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_handled_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='CZK', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=12),
        ),
    ]
