# Generated by Django 3.2.18 on 2026-09-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20260325_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entries_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='oris_club_entry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='oris_club_entry_last_modified_timestamp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='oris_club_service_entry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='oris_club_service_entry_last_modified_timestamp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
