
PERMISSION_VIEW_PAYMENT_PERIOD_LIST = 'view_payment_period_list'
PERMISSION_CREATE_PAYMENT_PERIOD = 'create_payment_period'
PERMISSION_EDIT_PAYMENT_PERIOD = 'edit_payment_period'
PERMISSION_VIEW_PAYMENT_PERIOD = 'view_payment_period'

PERMISSION_VIEW_ACCOUNT_LIST = 'view_account_list'
PERMISSION_EDIT_ACCOUNT = 'edit_account'
PERMISSION_VIEW_ACCOUNT = 'view_account'
PERMISSION_ADD_TRANSACTION = 'add_transaction'
PERMISSION_EDIT_TRANSACTION = 'edit_transaction'

PERMISSION_ADD_ROLE = 'add_role'
PERMISSION_CHANGE_ROLE = 'change_role'
PERMISSION_DELETE_ROLE = 'delete_role'
PERMISSION_VIEW_ROLE = 'view_role'

PERMISSION_VIEW_CHANGE_LOG = 'view_change_log'

PERMISSION_VIEW_EVENT_LIST = 'view_event_list'
PERMISSION_EDIT_EVENT = 'edit_event'
PERMISSION_VIEW_EVENT = 'view_event'

PERMS_LIST = [
    PERMISSION_VIEW_ACCOUNT_LIST,
    PERMISSION_EDIT_ACCOUNT,
    PERMISSION_VIEW_ACCOUNT,
    PERMISSION_ADD_TRANSACTION,
    PERMISSION_EDIT_TRANSACTION,
    PERMISSION_ADD_ROLE,
    PERMISSION_CHANGE_ROLE,
    PERMISSION_DELETE_ROLE,
    PERMISSION_VIEW_ROLE,
    PERMISSION_VIEW_CHANGE_LOG,
    PERMISSION_VIEW_EVENT_LIST,
    PERMISSION_EDIT_EVENT,
    PERMISSION_VIEW_EVENT,
    PERMISSION_VIEW_PAYMENT_PERIOD_LIST,
    PERMISSION_CREATE_PAYMENT_PERIOD,
    PERMISSION_EDIT_PAYMENT_PERIOD,
    PERMISSION_VIEW_PAYMENT_PERIOD,
]

