# Generated by Django 3.1.3 on 2020-11-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=7, unique=True, verbose_name='Registrační číslo')),
                ('gender', models.CharField(choices=[('MAN', 'Muž'), ('WOMAN', 'Žena'), ('OTHER', 'Jiné')], max_length=5, verbose_name='Pohlaví')),
                ('licence', models.CharField(max_length=5, verbose_name='Licence')),
                ('first_name', models.CharField(max_length=50, verbose_name='Křestní jméno')),
                ('last_name', models.CharField(max_length=50, verbose_name='Příjmení')),
                ('si', models.CharField(max_length=30, verbose_name='SI')),
                ('born_year', models.PositiveIntegerField(verbose_name='Ročník')),
                ('oris_id', models.PositiveIntegerField()),
                ('oris_paid', models.PositiveSmallIntegerField(verbose_name='ORIS Paid')),
                ('oris_club_id', models.PositiveIntegerField()),
                ('oris_fee', models.PositiveIntegerField()),
            ],
        ),
    ]
