# Generated by Django 3.1.3 on 2021-01-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Muž'), ('F', 'Žena')], max_length=5, verbose_name='Pohlaví'),
        ),
        migrations.AlterField(
            model_name='account',
            name='oris_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Částka')),
                ('description', models.TextField(verbose_name='Popis (Oddílový příspěvek, dres, startovné apod...)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
