# Generated by Django 3.1.3 on 2021-01-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210110_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_purpose',
            field=models.CharField(choices=[('CLUB_MEMBERSHIP', 'Oddílový příspěvek'), ('JINÉ', 'Jiné')], default='CLUB_MEMBERSHIP', max_length=50, verbose_name='Účel transakce'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.account'),
        ),
    ]
