# Generated by Django 3.1.3 on 2021-01-14 20:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210114_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_purpose',
            new_name='purpose',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Datum a čas vzniku'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Datum a čas poslední úpravy'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Částka'),
        ),
    ]
