# Generated by Django 3.1.3 on 2021-01-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210114_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_late_with_club_membership_payment',
            field=models.BooleanField(default=False),
        ),
    ]
