# Generated by Django 3.1.3 on 2021-03-01 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210123_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Datum a čas vzniku')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Datum a čas poslední úpravy')),
                ('date_from', models.DateField(verbose_name='Platnost od')),
                ('date_to', models.DateField(verbose_name='Platnost do')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.paymentperiod', verbose_name='Období'),
        ),
    ]
