# Generated by Django 3.1.3 on 2021-05-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210504_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='leader_key',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('CLUB_MEMBERSHIP', 'Oddílový příspěvek'), ('JINÉ', 'Jiné'), ('DLUHY', 'Dluhy')], default='CLUB_MEMBERSHIP', max_length=50, verbose_name='Účel transakce'),
        ),
    ]
