# Generated by Django 3.1.3 on 2021-05-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_entry_category_name'),
        ('account', '0010_auto_20210510_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='origin_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='entry.entry'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('CLUB_MEMBERSHIP', 'Oddílový příspěvek'), ('JINÉ', 'Jiné'), ('DLUHY', 'Dluhy'), ('ENTRY', 'Účast na závodech')], default='CLUB_MEMBERSHIP', max_length=50, verbose_name='Účel transakce'),
        ),
    ]
