# Generated by Django 3.1.3 on 2021-06-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='oris_club_member_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
