# Generated by Django 3.1.3 on 2021-10-20 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_account_oris_club_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('CLUB_MEMBERSHIP', 'Oddílový příspěvek'), ('JINÉ', 'Jiné'), ('DLUHY', 'Dluhy'), ('ENTRY', 'Účast na závodech'), ('ENTRY_OTHER', 'Další náklady na závodech')], default='CLUB_MEMBERSHIP', max_length=50, verbose_name='Účel transakce'),
        ),
    ]
