# Generated by Django 3.2.18 on 2023-04-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='leader_priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
