# Generated by Django 3.2.18 on 2024-02-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_account_leader_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clubroom_chip_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Číslo čipu od klubovny'),
        ),
    ]
