# Generated by Django 3.2.18 on 2024-03-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_account_clubroom_chip_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='clubroom_chip_number',
        ),
        migrations.AddField(
            model_name='account',
            name='clubroom_chip_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Číslo čipu od klubovny'),
            preserve_default=False,
        ),
    ]
