# Generated by Django 3.2.18 on 2024-04-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_account_clubroom_chip_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email2',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
