# Generated by Django 3.2.18 on 2024-06-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_banktransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='remote_id',
            field=models.CharField(db_index=True, default=None, max_length=255, unique=True, verbose_name='ID transakce'),
            preserve_default=False,
        ),
    ]
