# Generated by Django 3.2.18 on 2025-01-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_banktransaction_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='purpose',
            field=models.CharField(choices=[('CLUB_MEMBERSHIP', 'Oddílový příspěvek'), ('DEBTS', 'Dluhy')], default='DEBTS', max_length=50, verbose_name='Účel transakce'),
        ),
    ]
