# Generated by Django 3.2.18 on 2025-04-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_banktransaction_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='removed_from_google_workspace',
            field=models.BooleanField(default=False),
        ),
    ]
