# Generated by Django 3.2.18 on 2025-10-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_account_removed_from_google_workspace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentperiod',
            options={'ordering': ('-date_to',)},
        ),
        migrations.AddField(
            model_name='transaction',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Autor změny'),
        ),
    ]
