# Generated by Django 3.2.18 on 2026-01-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20251007_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_future',
            field=models.BooleanField(default=False, verbose_name='Budoucí transakce'),
        ),
    ]
