# Generated by Django 3.2.18 on 2026-01-28 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_transaction_is_future'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='receiver_note',
            field=models.TextField(blank=True, default='', verbose_name='Poznámka pro příjemce'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Jméno odesílatele'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_bank_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='account.banktransaction'),
        ),
    ]
