# Generated by Django 3.2.18 on 2026-02-06 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_add_bank_transaction_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='account.account'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='purpose',
            field=models.CharField(choices=[('CLUB_MEMBERSHIP', 'Oddílový příspěvek'), ('DEBTS', 'Dluhy'), ('UNKNOWN', 'Neznámý')], default='DEBTS', max_length=50, verbose_name='Účel transakce'),
        ),
    ]
