
ORIS_EVENTS_RESPONSE_DATA = {
    "Event_5712": {
        "ID": "5712",
        "Name": "Oblastní žebříček",
        "Date": "2020-10-25",
        "Org1": {
            "ID": "26",
            "Abbr": "DKL",
            "Name": "KOB Kladno"
        },
        "Org2": [],
        "Region": "P, StČ",
        "Regions": {
            "Region_P": {
                "ID": "P",
                "Name": "Pražská"
            },
            "Region_StČ": {
                "ID": "StČ",
                "Name": "Středočeská"
            }
        },
        "Sport": {
            "ID": "1",
            "NameCZ": "OB",
            "NameEN": "Foot O"
        },
        "Discipline": {
            "ID": "2",
            "ShortName": "KT",
            "NameCZ": "Krátká trať",
            "NameEN": "Middle distance"
        },
        "Level": {
            "ID": "4",
            "ShortName": "OŽ",
            "NameCZ": "Oblastní žebříček",
            "NameEN": "Local event"
        },
        "EntryDate1": "2020-10-20 23:59:59",
        "EntryDate2": "",
        "EntryDate3": "",
        "Ranking": "0",
        "SIType": {
            "ID": "1",
            "Name": "SI kontaktní"
        },
        "Cancelled": "1",
        "GPSLat": "50.1022",
        "GPSLon": "14.003",
        "Place": "Žilina, Na Píska 19",
        "Version": "14",
        "ClassesLastModifiedTimeStamp": 1601400337,
        "ServicesLastModifiedTimeStamp": 0,
        "ParentID": 0,
        "Status": "E",
        "OBPostupy": ""
    }
}

ORIS_EVENT_RESPONSE_DATA = {
    "ID": "5712",
    "Name": "Oblastní žebříček",
    "Date": "2020-10-25",
    "Place": "Žilina, Na Píska 19",
    "Map": "Oborka",
    "Org1": {
        "ID": "26",
        "Abbr": "DKL",
        "Name": "KOB Kladno"
    },
    "Org2": [],
    "Region": "P, StČ",
    "Regions": {
        "Region_P": {
            "ID": "P",
            "Name": "Pražská"
        },
        "Region_StČ": {
            "ID": "StČ",
            "Name": "Středočeská"
        }
    },
    "Sport": {
        "ID": "1",
        "NameCZ": "OB",
        "NameEN": "Foot O"
    },
    "Discipline": {
        "ID": "2",
        "ShortName": "KT",
        "NameCZ": "Krátká trať",
        "NameEN": "Middle distance"
    },
    "Level": {
        "ID": "4",
        "ShortName": "OŽ",
        "NameCZ": "Oblastní žebříček",
        "NameEN": "Local event"
    },
    "EntryDate1": "2020-10-20 23:59:59",
    "EntryDate2": "",
    "EntryDate3": "",
    "EntryInfo": "",
    "EntryDescCZ": "",
    "EntryDescEN": "",
    "EntryKoef2": "50",
    "EntryKoef3": "0",
    "EntryNoRegExtraKoef": "0",
    "EntryTotalLimit": "1000",
    "EntryWaitingQueue": "0",
    "EntryRentSIFee": "40",
    "EntryBankAccount": "2201220535/2010",
    "UseORISForEntries": "1",
    "Currency": "CZK",
    "SIType": {
        "ID": "1",
        "Name": "SI kontaktní"
    },
    "Ranking": "0",
    "RankingKoef": "",
    "RankingKS": "0",
    "RankingDecisionDate": "2020-09-30",
    "Cancelled": "1",
    "CancelledReason": "Zrušeno na základě USNESENÍ VLÁDY ČESKÉ REPUBLIKY ze dne 8. října 2020 č. 996 o přijetí krizového opatření",
    "StartTime": "10:30",
    "EventOfficeCloses": "09:30",
    "Protocol": "",
    "GPSLat": "50.1022",
    "GPSLon": "14.003",
    "RequestedStartForbidden": "0",
    "Version": "14",
    "Stages": "0",
    "Stage1": "0",
    "Stage2": "0",
    "Stage3": "0",
    "Stage4": "0",
    "Stage5": "0",
    "Stage6": "0",
    "Stage7": "0",
    "ParentID": None,
    "Director": {
        "ID": "774",
        "FirstName": "Pavel",
        "LastName": "Vinš"
    },
    "MainReferee": {
        "ID": "766",
        "FirstName": "Jiří",
        "LastName": "Cabrnoch"
    },
    "CourseSetter_1": {
        "ID": "774",
        "FirstName": "Pavel",
        "LastName": "Vinš"
    },
    "SW": {
        "ID": "773",
        "FirstName": "Jan",
        "LastName": "Beneš"
    },
    "EventInfo": "",
    "EventWarning": "",
    "Documents": {
        "Document_20344": {
            "ID": "20344",
            "Url": "https://oris.orientacnisporty.cz/files/5712_a10461930bd980dfa35e214620432939.pdf",
            "SourceType": {
                "ID": "1",
                "NameCZ": "Rozpis",
                "NameEN": "Invitation"
            },
            "OtherDescCZ": "",
            "OtherDescEN": ""
        }
    },
    "Links": [],
    "Locations": [],
    "Classes": {
        "Class_125509": {
            "ID": "125509",
            "Name": "D10",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "43",
                "AgeFrom": "0",
                "AgeTo": "10",
                "Gender": "F",
                "Name": "D10"
            },
            "Fee": "80",
            "NoExtraFee": "1",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "4",
            "CurrentResultsCount": "0"
        },
        "Class_125510": {
            "ID": "125510",
            "Name": "D10F",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "43",
                "AgeFrom": "0",
                "AgeTo": "10",
                "Gender": "F",
                "Name": "D10"
            },
            "Fee": "80",
            "NoExtraFee": "1",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "1",
            "CurrentResultsCount": "0"
        },
        "Class_125511": {
            "ID": "125511",
            "Name": "D12",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "44",
                "AgeFrom": "0",
                "AgeTo": "12",
                "Gender": "F",
                "Name": "D12"
            },
            "Fee": "80",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "13",
            "CurrentResultsCount": "0"
        },
        "Class_125512": {
            "ID": "125512",
            "Name": "D14",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "45",
                "AgeFrom": "0",
                "AgeTo": "14",
                "Gender": "F",
                "Name": "D14"
            },
            "Fee": "80",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "9",
            "CurrentResultsCount": "0"
        },
        "Class_125513": {
            "ID": "125513",
            "Name": "D16",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "46",
                "AgeFrom": "0",
                "AgeTo": "16",
                "Gender": "F",
                "Name": "D16"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "8",
            "CurrentResultsCount": "0"
        },
        "Class_125514": {
            "ID": "125514",
            "Name": "D18",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "47",
                "AgeFrom": "0",
                "AgeTo": "18",
                "Gender": "F",
                "Name": "D18"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "4",
            "CurrentResultsCount": "0"
        },
        "Class_125542": {
            "ID": "125542",
            "Name": "D20",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "48",
                "AgeFrom": "0",
                "AgeTo": "20",
                "Gender": "F",
                "Name": "D20"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "0",
            "CurrentResultsCount": "0"
        },
        "Class_125515": {
            "ID": "125515",
            "Name": "D21K",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "49",
                "AgeFrom": "0",
                "AgeTo": "99",
                "Gender": "F",
                "Name": "D21"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "0",
            "CurrentResultsCount": "0"
        },
        "Class_125516": {
            "ID": "125516",
            "Name": "D21L",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "49",
                "AgeFrom": "0",
                "AgeTo": "99",
                "Gender": "F",
                "Name": "D21"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "16",
            "CurrentResultsCount": "0"
        },
        "Class_125518": {
            "ID": "125518",
            "Name": "D35",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "75",
                "AgeFrom": "35",
                "AgeTo": "99",
                "Gender": "F",
                "Name": "D35"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "14",
            "CurrentResultsCount": "0"
        },
        "Class_125520": {
            "ID": "125520",
            "Name": "D45",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "51",
                "AgeFrom": "45",
                "AgeTo": "99",
                "Gender": "F",
                "Name": "D45"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "14",
            "CurrentResultsCount": "0"
        },
        "Class_125521": {
            "ID": "125521",
            "Name": "D55",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "53",
                "AgeFrom": "55",
                "AgeTo": "99",
                "Gender": "F",
                "Name": "D55"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "5",
            "CurrentResultsCount": "0"
        },
        "Class_125522": {
            "ID": "125522",
            "Name": "D65",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "55",
                "AgeFrom": "65",
                "AgeTo": "99",
                "Gender": "F",
                "Name": "D65"
            },
            "Fee": "80",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "4",
            "CurrentResultsCount": "0"
        },
        "Class_125523": {
            "ID": "125523",
            "Name": "D75",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "57",
                "AgeFrom": "75",
                "AgeTo": "99",
                "Gender": "F",
                "Name": "D75"
            },
            "Fee": "80",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "2",
            "CurrentResultsCount": "0"
        },
        "Class_125524": {
            "ID": "125524",
            "Name": "H10",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "1",
                "AgeFrom": "0",
                "AgeTo": "10",
                "Gender": "M",
                "Name": "H10"
            },
            "Fee": "80",
            "NoExtraFee": "1",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "3",
            "CurrentResultsCount": "0"
        },
        "Class_125525": {
            "ID": "125525",
            "Name": "H10F",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "1",
                "AgeFrom": "0",
                "AgeTo": "10",
                "Gender": "M",
                "Name": "H10"
            },
            "Fee": "80",
            "NoExtraFee": "1",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "4",
            "CurrentResultsCount": "0"
        },
        "Class_125526": {
            "ID": "125526",
            "Name": "H12",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "2",
                "AgeFrom": "0",
                "AgeTo": "12",
                "Gender": "M",
                "Name": "H12"
            },
            "Fee": "80",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "12",
            "CurrentResultsCount": "0"
        },
        "Class_125527": {
            "ID": "125527",
            "Name": "H14",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "4",
                "AgeFrom": "0",
                "AgeTo": "14",
                "Gender": "M",
                "Name": "H14"
            },
            "Fee": "80",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "12",
            "CurrentResultsCount": "0"
        },
        "Class_125528": {
            "ID": "125528",
            "Name": "H16",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "5",
                "AgeFrom": "0",
                "AgeTo": "16",
                "Gender": "M",
                "Name": "H16"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "5",
            "CurrentResultsCount": "0"
        },
        "Class_125529": {
            "ID": "125529",
            "Name": "H18",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "9",
                "AgeFrom": "0",
                "AgeTo": "18",
                "Gender": "M",
                "Name": "H18"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "4",
            "CurrentResultsCount": "0"
        },
        "Class_125543": {
            "ID": "125543",
            "Name": "H20",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "13",
                "AgeFrom": "0",
                "AgeTo": "20",
                "Gender": "M",
                "Name": "H20"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "1",
            "CurrentResultsCount": "0"
        },
        "Class_125530": {
            "ID": "125530",
            "Name": "H21K",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "18",
                "AgeFrom": "0",
                "AgeTo": "99",
                "Gender": "M",
                "Name": "H21"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "3",
            "CurrentResultsCount": "0"
        },
        "Class_125531": {
            "ID": "125531",
            "Name": "H21L",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "18",
                "AgeFrom": "0",
                "AgeTo": "99",
                "Gender": "M",
                "Name": "H21"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "10",
            "CurrentResultsCount": "0"
        },
        "Class_125533": {
            "ID": "125533",
            "Name": "H35",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "76",
                "AgeFrom": "35",
                "AgeTo": "99",
                "Gender": "M",
                "Name": "H35"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "15",
            "CurrentResultsCount": "0"
        },
        "Class_125535": {
            "ID": "125535",
            "Name": "H45",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "63",
                "AgeFrom": "45",
                "AgeTo": "99",
                "Gender": "M",
                "Name": "H45"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "10",
            "CurrentResultsCount": "0"
        },
        "Class_125536": {
            "ID": "125536",
            "Name": "H55",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "65",
                "AgeFrom": "55",
                "AgeTo": "99",
                "Gender": "M",
                "Name": "H55"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "8",
            "CurrentResultsCount": "0"
        },
        "Class_125537": {
            "ID": "125537",
            "Name": "H65",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "67",
                "AgeFrom": "65",
                "AgeTo": "99",
                "Gender": "M",
                "Name": "H65"
            },
            "Fee": "80",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "7",
            "CurrentResultsCount": "0"
        },
        "Class_125538": {
            "ID": "125538",
            "Name": "H75",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "69",
                "AgeFrom": "75",
                "AgeTo": "99",
                "Gender": "M",
                "Name": "H75"
            },
            "Fee": "80",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "1",
            "CurrentResultsCount": "0"
        },
        "Class_125539": {
            "ID": "125539",
            "Name": "HDR",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "119",
                "AgeFrom": "0",
                "AgeTo": "99",
                "Gender": "",
                "Name": "HDR"
            },
            "Fee": "80",
            "NoExtraFee": "1",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "2",
            "CurrentResultsCount": "0"
        },
        "Class_127758": {
            "ID": "127758",
            "Name": "T3",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "74",
                "AgeFrom": "0",
                "AgeTo": "99",
                "Gender": "",
                "Name": "OSTATNI"
            },
            "Fee": "120",
            "NoExtraFee": "0",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "4",
            "CurrentResultsCount": "0"
        },
        "Class_127757": {
            "ID": "127757",
            "Name": "TF",
            "Distance": "0.00",
            "Climbing": "0",
            "Controls": "0",
            "PreFormattedHeader": "",
            "Splits": 0,
            "ClassDefinition": {
                "ID": "74",
                "AgeFrom": "0",
                "AgeTo": "99",
                "Gender": "",
                "Name": "OSTATNI"
            },
            "Fee": "80",
            "NoExtraFee": "1",
            "ManualFee": "0",
            "ManualFeeEntryDate2": "0",
            "ManualFeeEntryDate3": "0",
            "NoRegManualFee": "0",
            "NoRegManualFeeEntryDate1": "0",
            "NoRegManualFeeEntryDate2": "0",
            "NoRegManualFeeEntryDate3": "0",
            "Ranking": "0",
            "RankingKoef": "0",
            "RankingKS": "0",
            "CurrentEntriesCount": "2",
            "CurrentResultsCount": "0"
        }
    },
    "Services": [],
    "CurrentEntriesCount": "197",
    "CurrentStartsCount": "0",
    "CurrentResultsCount": "0"
}